spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/DBSGLBOOKSTORE
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MariaDB10Dialect